### ISSUE TITLE
The guidance on the topic of this awesome article

### ISSUE THREAD

**Issue by PyGamma** [gibertgibs/Self-Motive4Tech#1]
First, appreciation for this wonderful piece in here, I would like to suggest a correction in the tittle of this article, instead of it being motivational quotes. You could put a more eye catching tittle e.g The key to Self Motivation. The above is just an example of how powerful your tittle should be but of course there is no limit to what you can create. Always be sure that great tittle catches you audioance in reading the entire article.

**Comment by gibertgibs** [comment]
It's okay, so I think I will take that of yours, that's the Key to Self motivation

**Comment by gibertgibs** [comment]
I think it's changed to The key to motivation already
