### ISSUE TITLE
The is problem with the way you are using read me file

### ISSUE THREAD

**Issue by PyGamma** [gibertgibs/Self-Motive4Tech#2]
Hey please try to make appropriate use of your read me file, it looks like you putting everything you want in the read me file when it is suppose to only contain a description of the repository. So please move most of this things in a separate file and leave the description of what the repository is about in the read me file

**Comment by gibertgibs** [comment]
Okay.... Probably I will work on that...Tonight

**Comment by PyGamma** [comment]
So far not bad thought but work on the following areas, the Grammer and fluency in the areas as highlighted in red in the attached screenshot
![Screenshot_20201206-085017](https://user-images.githubusercontent.com/38918594/101272771-65f85280-37a0-11eb-92e4-d2be0d194077.png)

**Comment by gibertgibs** [comment]
Okay....I am running on it right away

**Comment by PyGamma** [comment]
Look good for now.
Thanks for being a hard working person.

**Comment by PyGamma** [comment]
Looks good to now
