### ISSUE TITLE
What if instead of creating my files in the code, I use the wiki pages?

### ISSUE THREAD

**Issue by gibertgibs** [gibertgibs/Self-Motive4Tech#3]
Okay, am just curious of the difference between the wiki and the codes.... Because wiki seems to be more organized to me than codes...It gives room for one to edit the home page and then the rest of the pages.
So what is the purpose of the wiki pages?
And what is the purpose of the codes?

**Comment by timmwille** [comment]
dependes → Code is your Project, Readme gives an Overview and the wiki provides the documentation on how to use and work with the project files
https://guides.github.com/features/wikis/

→ the better management and collaboration is always via the code section as it manages the files, the wiki is just managing the text focused.

**Comment by gibertgibs** [comment]
Precisely the ready and finalised document is to be in the wiki while the ones being worked upon remains in the code.

**Comment by PyGamma** [comment]
Thanks Gilbert for your question and patience as well, the key to what to use for scripting you files depends on the original design of the tool used, wiki is a documentation host tool that github has that allows you to host your project documentation, you see when you develop any solution, besides the read me file which serves to give brief outline of what your repository is about to repository visitors, you will need to develop a web site containing documentation concerning the project but GitHub has volunteered to help you document all necessary information about you projects in the wiki hosted by github it self. By adding you file in the wiki you are using github tool to host you documentations. So it is clear that the tool should be used for documentation not for scripting you content thought the fantasy and feels of the beautiful looks might be tempting, you shouldn't foreshake purpose for looks and feels. Besides that you are learning GitHub and you might get involved in other bigger project that might need professional use of the platform so learning not to use the right feature for the rightful purpose might become a vice in the long run.

**Comment by gibertgibs** [comment]
Thanks slot I think this is already solved
